M48
; DRILL file {KiCad 7.0.9-7.0.9~ubuntu22.04.1} date Fri 29 Dec 2023 03:53:21 PM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-29T15:53:21-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9-7.0.9~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.15Y-4.2
X1.15Y-6.65
X5.45Y-4.2
X5.45Y-6.65
T0
M30
