M48
; DRILL file {KiCad 6.0.9-8da3e8f707~117~ubuntu22.04.1} date Mon 02 Jan 2023 03:35:45 PM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-02T15:35:45-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9-8da3e8f707~117~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.15Y-4.2
X1.15Y-6.65
X5.45Y-4.2
X5.45Y-6.65
T0
M30
